INSERT INTO cliente(ID, IDENTIFICACION, NOMBRE, GENERO, EDAD, DIRECCION, TELEFONO,CONTRASENA, ESTADO)
VALUES (1, '12345', 'Jose Lema', 'Masculino', '56', 'Otavalo sn y principal', '098254785','1234', true);

INSERT INTO cliente(ID, IDENTIFICACION, NOMBRE, GENERO, EDAD, DIRECCION, TELEFONO,CONTRASENA, ESTADO)
VALUES (2, '65478', 'Marianela Montalvo', 'Femenina', '25', 'Amazonas y NNUU', '097548965','5678', true);

INSERT INTO cliente(ID, IDENTIFICACION, NOMBRE, GENERO, EDAD, DIRECCION, TELEFONO,CONTRASENA, ESTADO)
VALUES (2, '91011', 'Juan Osorio', 'Masculino', '56', '13 junio y Equinoccial', '098874587','1245', true);


INSERT INTO cuenta(ID, NUMERO_CUENTA, TIPO_CUENTA, SALDO_INICIAL, ESTADO, CLIENTE_ID)
VALUES (1, '478758', 'Ahorro', '2000', true, 1);

INSERT INTO cuenta(ID, NUMERO_CUENTA, TIPO_CUENTA, SALDO_INICIAL, ESTADO, CLIENTE_ID)
VALUES (2, '225487', 'Corriente', '100', true, 2);

INSERT INTO cuenta(ID, NUMERO_CUENTA, TIPO_CUENTA, SALDO_INICIAL, ESTADO, CLIENTE_ID)
VALUES (3, '495878', 'Ahorro', '0', true, 3);

INSERT INTO cuenta(ID, NUMERO_CUENTA, TIPO_CUENTA, SALDO_INICIAL, ESTADO, CLIENTE_ID)
VALUES (4, '496825', 'Ahorro', '540', true, 2);

