CREATE TABLE cliente(id BIGINT NOT NULL, identificacion VARCHAR(50), nombre VARCHAR(50), genero VARCHAR(30),
 edad INT NOT NULL, direccion VARCHAR(50), telefono VARCHAR(50), contrasena VARCHAR(50), estado BOOLEAN DEFAULT TRUE NOT NULL);

INSERT INTO cliente(ID, IDENTIFICACION, NOMBRE, GENERO, EDAD, DIRECCION, TELEFONO, CONTRASENA, ESTADO)
VALUES (1, '12345', 'Joses Lema', 'Masculino', '56', 'Otavalo sn y principal', '098254785','1234', true);

INSERT INTO cliente(ID, IDENTIFICACION, NOMBRE, GENERO, EDAD, DIRECCION, TELEFONO, CONTRASENA, ESTADO)
VALUES (2, '65478', 'Marianela Montalvo', 'Femenina', '25', 'Amazonas y NNUU', '097548965','5678', true);

INSERT INTO cliente(ID, IDENTIFICACION, NOMBRE, GENERO, EDAD, DIRECCION, TELEFONO,CONTRASENA, ESTADO)
VALUES (3, '91011', 'Juan Osorio', 'Masculino', '56', '13 junio y Equinoccial', '098874587','1245', true);



